version: "3"

services:
    smart-pos:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: smart-pos
        volumes:
            - type: bind
              source: .
              target: /srv/app
            - /srv/app/node_modules

        ports:
            - 3000:3000