"use client "
import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/toaster"
import "./globals.css";
// import Footer from "@/components/Footer";


const lexend = Lexend({
  subsets: ['latin'],
  weight: ['200', '300', '400', '700', '800', '900'],
});



export const metadata: Metadata = {
  title: "Mobilis web portail",
  description: "Generated by Mobilis smart pos",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body
      
        className={cn(lexend.className , 'antialiased pt-4')}>
    
        {children}
        <Toaster />
      </body>
    </html>
  );
}
